import React from 'react';
import { ArrowRight, Cake, Users, Gift, Heart, PartyPopper } from 'lucide-react';
import { CATERING_CAKE_IMAGE, POLAROID_CUPCAKES_IMAGE, POLAROID_BOX_IMAGE } from '../data/desserts';
import { SparkleDoodle, HeartDoodle, WavyCreamDivider, WashiTape } from './DessertDoodles';

interface CateringSectionProps { onOpenCatering: () => void; }

export const CateringSection: React.FC<CateringSectionProps> = ({ onOpenCatering }) => {
  const items=[{icon:Cake,label:'Custom Cakes'},{icon:Users,label:'Events & Catering'},{icon:Gift,label:'Birthdays'},{icon:Heart,label:'Corporate Orders'},{icon:PartyPopper,label:'Any Occasion'}];
  return <section id="catering" className="relative bg-gradient-to-br from-[#FFF7ED] via-[#FDEBD7] to-[#F7D5BF] py-20 sm:py-28 overflow-hidden text-[#2B1410]">
    <div className="absolute -left-32 top-10 w-[520px] h-[520px] bg-[#D97706]/12 blur-3xl rounded-full"/><div className="absolute -right-28 bottom-0 w-[520px] h-[520px] bg-[#E11D48]/12 blur-3xl rounded-full"/>
    <div className="max-w-[1380px] mx-auto px-4 sm:px-6 lg:px-10 relative z-10 grid lg:grid-cols-12 gap-8 items-center">
      <div className="lg:col-span-4 relative"><div className="absolute -top-5 left-1/2 -translate-x-1/2 z-20"><WashiTape className="w-28 h-5" color="#FDE68A"/></div><div className="rounded-[40px] overflow-hidden shadow-2xl border-4 border-white rotate-[-2deg]"><img src={CATERING_CAKE_IMAGE} alt="Custom celebration cake" className="w-full aspect-[4/5] object-cover"/></div><div className="absolute -bottom-5 -left-2 bg-white/95 p-4 rounded-3xl shadow-xl rotate-[-5deg]"><p className="font-script text-2xl text-[#9E1236] font-bold leading-tight">Custom Cakes for<br/>Life's Sweetest Moments ♡</p></div></div>
      <div className="lg:col-span-5 text-center px-2"><p className="text-[11px] sm:text-xs font-extrabold uppercase tracking-[.24em] text-[#8A4A3E]">BIRTHDAYS • CELEBRATIONS • CORPORATE • JUST BECAUSE</p><h2 className="font-serif text-4xl sm:text-5xl lg:text-6xl font-bold mt-3 leading-[.98]">Planning<br/><span className="font-script text-[#9E1236] text-[1.15em]">Something Sweet?</span></h2><p className="mt-5 max-w-xl mx-auto text-[#5B3027] leading-relaxed font-medium">From custom cakes to dessert trays and catering, Chubby Dips makes every event a little more delicious.</p><button onClick={onOpenCatering} className="mt-7 px-7 py-3.5 bg-[#9E1236] text-white rounded-full font-bold inline-flex items-center gap-2 shadow-lg hover:bg-[#800F2B] transition">Request Catering <ArrowRight className="w-4 h-4"/></button><div className="mt-8 grid grid-cols-2 sm:grid-cols-5 gap-3">{items.map(({icon:Icon,label})=><div key={label} className="flex flex-col items-center text-center"><div className="w-10 h-10 bg-white rounded-full shadow-sm flex items-center justify-center text-[#9E1236]"><Icon className="w-5 h-5"/></div><span className="text-[11px] font-bold mt-2 text-[#4A261F]">{label}</span></div>)}</div></div>
      <div className="lg:col-span-3 relative min-h-[430px] hidden md:block"><figure className="absolute top-0 left-0 bg-white p-3 pb-8 shadow-2xl rotate-[-5deg] w-[82%]"><img src={POLAROID_CUPCAKES_IMAGE} alt="Cupcakes" className="w-full aspect-square object-cover"/><figcaption className="font-script text-xl text-[#9E1236] font-bold mt-2 text-center">Good Food<br/>Brings People Together ♡</figcaption></figure><figure className="absolute bottom-0 right-0 bg-white p-3 pb-8 shadow-2xl rotate-[6deg] w-[78%]"><img src={POLAROID_BOX_IMAGE} alt="Dessert box" className="w-full aspect-square object-cover"/><figcaption className="font-script text-xl text-[#9E1236] font-bold mt-2 text-center">Desserts Make<br/>Everything Better ♡</figcaption></figure></div>
    </div>
    <div className="absolute bottom-0 left-0 right-0"><WavyCreamDivider fillColor="#FFF8F4" className="w-full h-16 sm:h-20"/></div>
  </section>;
};
