import React, { useState } from 'react';
import { HERO_IMAGE, HERO_FALLBACK_IMAGE, HIGHLIGHT_PRODUCTS } from '../data/desserts';
import { ArrowRight, Calendar, Sprout, Heart, Award, Users } from 'lucide-react';
import { SparkleDoodle, StarClusterDoodle, HeartDoodle, StrawberryDoodle, ArrowDoodle, HoustonStamp, WavyCreamDivider, SprinkleCluster, FrostingDripBand, WashiTape, CutoutBerryIllustration } from './DessertDoodles';

interface HeroProps { onOpenMenu: () => void; onOpenOrder: () => void; }

export const Hero: React.FC<HeroProps> = ({ onOpenMenu, onOpenOrder }) => {
  const [heroImgSrc, setHeroImgSrc] = useState<string>(HERO_IMAGE);
  const trustFeatures = [
    { id: 'trust-fresh', icon: Sprout, title: 'Made Fresh', subtitle: 'in Houston' },
    { id: 'trust-custom', icon: Heart, title: 'Custom Orders', subtitle: '& Events' },
    { id: 'trust-quality', icon: Award, title: 'Quality', subtitle: 'Ingredients' },
    { id: 'trust-lead-time', icon: Users, title: '3–4 Day', subtitle: 'Lead Time' },
  ];
  const berryImage = HIGHLIGHT_PRODUCTS[0]?.image || HERO_FALLBACK_IMAGE;
  return (
    <section id="home" className="relative overflow-visible bg-gradient-to-b from-[#FFF5F0] via-[#FDF0E6] to-[#FAE4DA] pt-4 sm:pt-8 pb-24 sm:pb-36">
      <div className="absolute inset-0 bg-sprinkles opacity-40 pointer-events-none -z-0" />
      <div className="absolute -top-16 -right-24 w-[700px] h-[700px] bg-gradient-to-br from-[#FECDD3] via-[#FDA4AF]/50 to-[#F43F5E]/25 rounded-full blur-3xl pointer-events-none animate-pulse-glow" />
      <div className="absolute top-1/4 -left-28 w-[600px] h-[600px] bg-gradient-to-tr from-[#FED7AA]/60 via-[#FDBA74]/35 to-transparent rounded-full blur-3xl pointer-events-none" />
      <div className="absolute top-10 right-4 lg:right-16 w-[560px] h-[560px] bg-gradient-to-tr from-[#FFF2EA] via-[#FCE7F3]/70 to-[#FFF7ED] rounded-[70px] rotate-6 pointer-events-none border-4 border-white/80 shadow-[0_20px_50px_rgba(225,29,72,0.15)] blur-[1px]" />
      <div className="absolute top-1/2 left-0 right-0 h-40 bg-gradient-to-r from-transparent via-[#FDE047]/10 to-transparent -rotate-1 pointer-events-none" />
      <div className="absolute top-8 left-8 sm:left-24 pointer-events-none animate-sweet-float hidden sm:block"><SparkleDoodle className="w-10 h-10 opacity-80" color="#E11D48" /></div>
      <div className="absolute top-1/4 left-6 pointer-events-none animate-sweet-float-reverse hidden md:block"><HeartDoodle className="w-10 h-10 opacity-75" color="#F43F5E" /></div>
      <div className="absolute top-12 left-1/2 pointer-events-none animate-sweet-float hidden lg:block"><StrawberryDoodle className="w-12 h-14 opacity-85 transform rotate-12" /></div>
      <div className="absolute top-20 right-1/4 pointer-events-none hidden xl:block"><SprinkleCluster className="w-24 h-16 opacity-75" /></div>
      <div className="absolute bottom-32 left-1/3 pointer-events-none animate-sweet-float-reverse hidden md:block"><StarClusterDoodle className="w-10 h-10 opacity-75" /></div>
      <div className="max-w-[1380px] mx-auto px-4 sm:px-6 lg:px-10 relative z-10">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-6 items-center">
          <div className="lg:col-span-6 xl:col-span-5 flex flex-col text-left pt-2 lg:pt-4 z-20">
            <div className="mb-3 sm:mb-4 flex items-center gap-2"><span className="text-base">🍓</span><span className="text-[10.5px] sm:text-[12px] font-extrabold uppercase tracking-[0.28em] text-[#4A1D16] inline-block font-sans">CUSTOM CAKES &bull; DESSERT TRAYS &bull; CHOCOLATE TREATS</span></div>
            <h1 className="font-serif text-[44px] sm:text-[60px] lg:text-[70px] xl:text-[78px] leading-[1.02] text-[#240F0B] font-bold tracking-tight mb-4 sm:mb-6 drop-shadow-xs">Desserts worth <br /><span className="font-script text-[56px] sm:text-[74px] lg:text-[88px] xl:text-[102px] text-[#9E1236] font-normal leading-[0.88] tracking-normal inline-flex items-baseline relative">making room for.<span className="inline-block ml-2 text-4xl sm:text-5xl lg:text-6xl text-[#E11D48] font-normal transform -rotate-12 select-none animate-bounce duration-1000">♡</span></span></h1>
            <div className="relative mb-6 sm:mb-8"><p className="text-base sm:text-lg text-[#4A2219] leading-relaxed max-w-lg font-medium">Custom celebration cakes, overflowing dessert trays, chocolate-drenched berries and hand-dipped specialties — freshly made in Houston, Texas.</p><div className="hidden sm:flex items-center gap-1.5 absolute -bottom-7 right-6 pointer-events-none transform rotate-3"><span className="font-script text-2xl text-[#BE123C] font-bold whitespace-nowrap">Fresh batches daily!</span><ArrowDoodle className="w-8 h-8 text-[#BE123C] -mt-1" color="#BE123C" /></div></div>
            <div className="flex flex-wrap items-center gap-4 mb-8 pt-2"><button id="hero-cta-view-menu" onClick={onOpenMenu} className="px-8 py-3.5 rounded-full bg-gradient-to-r from-[#9E1236] to-[#BE123C] hover:from-[#881337] hover:to-[#9E1236] text-white font-bold text-base tracking-tight transition-all duration-200 shadow-[0_10px_25px_rgba(158,18,54,0.35)] hover:shadow-[0_16px_32px_rgba(158,18,54,0.45)] cursor-pointer flex items-center gap-2 group active:scale-95"><span>View Menu</span><ArrowRight className="w-4 h-4 transition-transform group-hover:translate-x-1.5" /></button><button id="hero-cta-request-order" onClick={onOpenOrder} className="px-7 py-3.5 rounded-full bg-white hover:bg-[#FFF5F2] text-[#9E1236] border-2 border-[#9E1236] font-bold text-base tracking-tight transition-all duration-200 shadow-sm hover:shadow-md cursor-pointer flex items-center gap-2.5 active:scale-95"><Calendar className="w-4 h-4 text-[#9E1236]" /><span>Request an Order</span></button></div>
            <div id="hero-trust-features" className="grid grid-cols-2 sm:grid-cols-4 gap-2.5 sm:gap-3 bg-white/90 backdrop-blur-md p-3 sm:p-4 rounded-3xl border border-[#F6D0C7] shadow-[0_8px_20px_rgba(43,20,16,0.06)]">{trustFeatures.map((feat) => { const IconComp = feat.icon; return <div key={feat.id} id={feat.id} className="flex flex-col items-center sm:items-start text-center sm:text-left p-1.5"><div className="w-8 h-8 rounded-full bg-[#FFF0EC] text-[#9E1236] flex items-center justify-center mb-1.5 shadow-2xs"><IconComp className="w-4 h-4" strokeWidth={2.2} /></div><p className="text-[12.5px] font-bold text-[#240F0B] leading-tight">{feat.title}</p><p className="text-[10.5px] text-[#7A3E31] font-medium leading-tight">{feat.subtitle}</p></div>; })}</div>
          </div>
          <div className="lg:col-span-6 xl:col-span-7 relative mt-8 lg:mt-0 flex justify-center lg:justify-end">
            <div className="absolute -top-10 sm:-top-12 right-2 sm:right-10 z-40 pointer-events-none transform rotate-3"><span className="font-script text-3xl sm:text-4xl lg:text-5xl text-[#9E1236] font-bold drop-shadow-xs flex items-center gap-1.5">Life is Sweeter Here ♡</span></div>
            <div className="absolute -top-12 -left-6 sm:-left-10 z-40 pointer-events-none hidden sm:block"><HoustonStamp className="w-24 h-24 sm:w-28 sm:h-28" /></div>
            <div className="relative w-full max-w-xl lg:max-w-none lg:w-[120%] xl:w-[128%] lg:-mr-16 xl:-mr-22">
              <div className="absolute -inset-4 sm:-inset-5 bg-gradient-to-tr from-[#FECDD3] via-[#FED7AA] to-[#FDE047]/40 rounded-[44px] sm:rounded-[60px] -rotate-2 opacity-80 blur-xs shadow-sweet" /><div className="absolute -inset-2 sm:-inset-3 bg-white rounded-[40px] sm:rounded-[56px] rotate-1 shadow-[0_20px_45px_rgba(158,18,54,0.18)]" />
              <div id="hero-breakout-berry-moment" className="absolute -top-5 -left-3 sm:-top-7 sm:-left-7 z-40 group/sub cursor-pointer transform -rotate-6 hover:rotate-0 transition-transform duration-300 select-none"><div className="absolute -top-2.5 left-1/2 -translate-x-1/2 z-50"><WashiTape className="w-18 h-4" color="#FED7AA" /></div><div className="relative w-20 h-20 sm:w-26 sm:h-26 rounded-full border-3 sm:border-4 border-white shadow-[0_12px_28px_rgba(43,20,16,0.28)] overflow-hidden bg-[#3D1A14]"><img src={berryImage} alt="Belgian chocolate hand-dipped berries close up" className="w-full h-full object-cover object-center transform transition-transform duration-500 group-hover/sub:scale-110" /><div className="absolute inset-0 bg-gradient-to-t from-black/50 via-transparent to-transparent pointer-events-none" /></div><div className="absolute -bottom-1.5 left-1/2 -translate-x-1/2 whitespace-nowrap bg-white/95 backdrop-blur-xs px-2.5 py-0.5 rounded-full border border-[#F6B8B0] shadow-2xs pointer-events-none"><span className="text-[9.5px] sm:text-[10.5px] font-extrabold text-[#9E1236]">Belgian Dip 🍓</span></div></div>
              <div className="absolute -top-5 -right-2 sm:-top-7 sm:-right-4 z-40 pointer-events-none transform rotate-12 hover:rotate-6 transition-transform"><CutoutBerryIllustration className="w-13 h-15 sm:w-16 sm:h-18" /><div className="absolute -bottom-1 -left-1"><SparkleDoodle className="w-5 h-5" color="#F59E0B" /></div></div>
              <div className="relative rounded-[40px] sm:rounded-[56px] overflow-hidden shadow-[0_35px_80px_rgba(43,20,16,0.34)] border-4 sm:border-8 border-white bg-[#FFF0EA] group"><div className="absolute top-0 left-0 right-0 z-20 pointer-events-none"><FrostingDripBand fillColor="#FFFFFF" className="w-full h-8 sm:h-11" dropShadow={false} /></div><div className="absolute top-5 right-5 sm:top-7 sm:right-7 z-20 bg-white/95 backdrop-blur-md px-4 py-1.5 rounded-full border border-[#FADCD5] shadow-sweet flex items-center gap-2 transform rotate-2 pointer-events-none"><span className="text-sm">🍓</span><span className="text-[10.5px] sm:text-[11.5px] font-extrabold uppercase tracking-[0.2em] text-[#9E1236]">Signature Drip &bull; Handcrafted Daily</span></div><img id="hero-dessert-photo" src={heroImgSrc} onError={() => { if (heroImgSrc !== HERO_FALLBACK_IMAGE) setHeroImgSrc(HERO_FALLBACK_IMAGE); }} alt="Extravagant celebration drip cake layered with fresh strawberries, raspberries, macarons, silky frosting, and chocolate drizzle by Chubby Dips Houston" className="w-full h-[480px] sm:h-[580px] lg:h-[650px] xl:h-[700px] object-cover object-center transform transition-transform duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-[#240F0B]/45 via-transparent to-transparent pointer-events-none" /><div className="absolute inset-0 ring-1 ring-inset ring-black/10 rounded-[40px] sm:rounded-[56px] pointer-events-none" /></div>
              <div id="hero-recipe-index-sheet" className="absolute -bottom-8 -left-3 sm:-bottom-10 sm:-left-12 z-40 bg-[#FFFDF9] border border-[#F6D0C7] rounded-2xl p-3 sm:p-4 shadow-[0_20px_45px_rgba(43,20,16,0.22)] max-w-[240px] sm:max-w-[280px] transform -rotate-2 hover:rotate-0 transition-transform duration-300 pointer-events-none sm:pointer-events-auto"><div className="absolute -top-2.5 left-4"><WashiTape className="w-18 h-4.5" color="#FDE68A" /></div><div className="flex items-center justify-between border-b border-[#F5DDD5] pb-1 mb-1.5 pt-1"><span className="text-[9.5px] font-black uppercase tracking-[0.2em] text-[#9E1236]">✦ TODAY'S BATCH &bull; NO. 042</span><span className="text-xs">✨</span></div><p className="font-serif text-sm sm:text-[15px] font-bold text-[#240F0B] leading-tight mb-1.5">Triple-Layer Celebration Drip</p><ul className="text-[11px] text-[#552A20] space-y-0.5 font-medium leading-tight"><li className="flex items-center gap-1.5"><span className="text-[#9E1236] font-bold">&bull;</span><span>70% Belgian chocolate berry drip</span></li><li className="flex items-center gap-1.5"><span className="text-[#9E1236] font-bold">&bull;</span><span>Farm strawberries &amp; French macarons</span></li><li className="flex items-center gap-1.5"><span className="text-[#9E1236] font-bold">&bull;</span><span>Whipped vanilla bean buttercream</span></li></ul><div className="mt-2 pt-1 border-t border-dashed border-[#F5DDD5] flex items-center justify-between text-[10px] text-[#9E1236] font-bold"><span className="font-script text-base text-[#BE123C]">Handcrafted with love ♡</span><span>6:00 AM</span></div></div>
              <div id="hero-playful-badge" className="absolute -bottom-6 sm:-bottom-8 -right-2 sm:-right-5 z-40 bg-gradient-to-r from-[#FCE6E2] via-[#FFF0EC] to-[#FED7AA] border-2 border-[#F6B8B0] px-5 sm:px-7 py-3 sm:py-4 rounded-3xl shadow-[0_15px_35px_rgba(158,18,54,0.22)] transform -rotate-3 hover:rotate-0 transition-transform duration-300"><p className="font-script text-2xl sm:text-3xl lg:text-4xl text-[#9E1236] font-bold leading-[1.05] text-center">Good Desserts <br /><span className="text-[#881337]">Happier People ♡</span></p></div>
              <div className="absolute -bottom-2 left-2 sm:-bottom-3 sm:left-4 z-40 bg-white p-2 sm:p-3 rounded-full shadow-sweet border border-[#FBD6DA] animate-sweet-float pointer-events-none"><span className="text-xl sm:text-2xl leading-none select-none">🍓</span></div>
            </div>
          </div>
        </div>
      </div>
      <div className="w-full overflow-hidden leading-none absolute bottom-0 left-0 right-0 pointer-events-none translate-y-px z-10"><WavyCreamDivider fillColor="#7A0D28" className="w-full h-14 sm:h-22" /></div>
    </section>
  );
};
