import React, { useState } from 'react';
import { X, Search, ArrowRight } from 'lucide-react';
import { HIGHLIGHT_PRODUCTS, MENU_CATEGORIES } from '../data/desserts';
import { Product } from '../types';

interface MenuModalProps { isOpen:boolean; onClose:()=>void; onSelectProduct:(p:Product)=>void; onRequestOrder:(treat?:string)=>void; }
export const MenuModal:React.FC<MenuModalProps>=({isOpen,onClose,onSelectProduct,onRequestOrder})=>{
  const [cat,setCat]=useState('all'); const [q,setQ]=useState(''); if(!isOpen)return null;
  const list=HIGHLIGHT_PRODUCTS.filter(p=>(cat==='all'||p.category===cat)&&p.name.toLowerCase().includes(q.toLowerCase()));
  return <div className="fixed inset-0 z-[100] bg-[#2B1410]/70 backdrop-blur-sm p-4 sm:p-8 overflow-y-auto" onMouseDown={onClose}><div className="max-w-5xl mx-auto bg-[#FFF8F4] rounded-[36px] shadow-2xl overflow-hidden" onMouseDown={e=>e.stopPropagation()}><div className="p-5 sm:p-7 border-b border-[#F5DDD5] flex items-center justify-between"><div><p className="font-script text-2xl text-[#9E1236]">Pick your favorite ♡</p><h2 className="font-serif text-3xl sm:text-4xl font-bold text-[#240F0B]">Dessert Menu</h2></div><button onClick={onClose} className="w-10 h-10 bg-white rounded-full flex items-center justify-center shadow-sm"><X/></button></div><div className="p-5 sm:p-7"><div className="relative mb-4"><Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-[#8A4A3E]"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search desserts..." className="w-full bg-white rounded-full border border-[#F3D7CE] py-3 pl-11 pr-4 outline-none"/></div><div className="flex gap-2 overflow-x-auto pb-4">{MENU_CATEGORIES.map(c=><button key={c.id} onClick={()=>setCat(c.id)} className={`whitespace-nowrap px-4 py-2 rounded-full text-xs font-bold ${cat===c.id?'bg-[#9E1236] text-white':'bg-white text-[#4A261F] border border-[#F3D7CE]'}`}>{c.label}</button>)}</div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{list.map(p=><article key={p.id} onClick={()=>onSelectProduct(p)} className="bg-white rounded-3xl overflow-hidden border border-[#F3D7CE] cursor-pointer"><img src={p.image} className="w-full aspect-[4/3] object-cover"/><div className="p-4"><h3 className="font-serif text-xl font-bold">{p.name}</h3><p className="text-xs text-[#6B3A30] mt-1 line-clamp-2">{p.description}</p><div className="mt-3 flex justify-between items-center"><b className="text-[#9E1236]">{p.priceTag}</b><button onClick={e=>{e.stopPropagation();onRequestOrder(p.name)}} className="text-xs font-bold flex items-center gap-1">Order <ArrowRight className="w-3 h-3"/></button></div></div></article>)}</div></div></div></div>;
};
