import React, { useEffect, useState } from 'react';
import { X, Calendar, Mail, User, Phone, ArrowRight, CheckCircle2 } from 'lucide-react';

interface OrderModalProps { isOpen:boolean; onClose:()=>void; initialTreat?:string; }
export const OrderModal:React.FC<OrderModalProps>=({isOpen,onClose,initialTreat})=>{
  const [sent,setSent]=useState(false); const [treat,setTreat]=useState(initialTreat||'');
  useEffect(()=>{setTreat(initialTreat||'');setSent(false)},[initialTreat,isOpen]); if(!isOpen)return null;
  return <div className="fixed inset-0 z-[110] bg-[#2B1410]/70 backdrop-blur-sm p-4 overflow-y-auto" onMouseDown={onClose}><div className="max-w-2xl mx-auto my-8 bg-[#FFF8F4] rounded-[36px] shadow-2xl" onMouseDown={e=>e.stopPropagation()}><div className="p-6 sm:p-8 border-b border-[#F5DDD5] flex justify-between"><div><p className="font-script text-2xl text-[#9E1236]">Let's make something sweet ♡</p><h2 className="font-serif text-3xl sm:text-4xl font-bold">Request an Order</h2></div><button onClick={onClose} className="w-10 h-10 bg-white rounded-full flex items-center justify-center"><X/></button></div>{sent?<div className="p-12 text-center"><CheckCircle2 className="w-14 h-14 text-[#9E1236] mx-auto"/><h3 className="font-serif text-3xl font-bold mt-4">Sweet request received!</h3><p className="text-[#6B3A30] mt-2">This concept form does not send a live order. Chubby Dips would follow up to confirm details.</p><button onClick={onClose} className="mt-6 bg-[#9E1236] text-white px-6 py-3 rounded-full font-bold">Close</button></div>:<form onSubmit={e=>{e.preventDefault();setSent(true)}} className="p-6 sm:p-8 grid sm:grid-cols-2 gap-4"><label className="sm:col-span-2"><span className="text-xs font-bold">What are you craving?</span><input value={treat} onChange={e=>setTreat(e.target.value)} className="mt-1 w-full bg-white border border-[#F3D7CE] rounded-2xl px-4 py-3" placeholder="Custom cake, berries, dessert tray..."/></label><label><span className="text-xs font-bold">Full name</span><input required className="mt-1 w-full bg-white border border-[#F3D7CE] rounded-2xl px-4 py-3"/></label><label><span className="text-xs font-bold">Email</span><input required type="email" className="mt-1 w-full bg-white border border-[#F3D7CE] rounded-2xl px-4 py-3"/></label><label><span className="text-xs font-bold">Phone</span><input className="mt-1 w-full bg-white border border-[#F3D7CE] rounded-2xl px-4 py-3"/></label><label><span className="text-xs font-bold">Event date</span><input type="date" className="mt-1 w-full bg-white border border-[#F3D7CE] rounded-2xl px-4 py-3"/></label><label className="sm:col-span-2"><span className="text-xs font-bold">Theme, colors or special requests</span><textarea rows={4} className="mt-1 w-full bg-white border border-[#F3D7CE] rounded-2xl px-4 py-3"/></label><button className="sm:col-span-2 mt-2 bg-[#9E1236] text-white rounded-full py-3.5 font-bold flex items-center justify-center gap-2">Send Sweet Request <ArrowRight className="w-4 h-4"/></button></form>}</div></div>;
};
