import React from 'react';
import { Product } from '../types';
import { HIGHLIGHT_PRODUCTS } from '../data/desserts';
import { Heart, Sparkles, ArrowRight } from 'lucide-react';
import { SparkleDoodle, HeartDoodle, StrawberryDoodle, WavyCreamDivider, WashiTape } from './DessertDoodles';

interface ProductGridProps {
  onSelectProduct: (product: Product) => void;
  onQuickOrder: (product: Product) => void;
  favorites: string[];
  onToggleFavorite: (productId: string) => void;
}

export const ProductGrid: React.FC<ProductGridProps> = ({ onSelectProduct, onQuickOrder, favorites, onToggleFavorite }) => {
  const p = (id: string) => HIGHLIGHT_PRODUCTS.find(x => x.id === id) || HIGHLIGHT_PRODUCTS[0];
  const strawberries=p('choc-strawberries'), unicorn=p('unicorn-cake'), birthday=p('birthday-cake'), cupcake=p('cupcake-classic'), strawberry=p('strawberry-delight'), champagne=p('champagne-truffles'), pumpkin=p('pumpkin-treat'), pretzel=p('pretzel-twists'), upside=p('upside-down-cake'), ginger=p('gingerbread-house');
  const heart = (product: Product) => <button onClick={e=>{e.stopPropagation();onToggleFavorite(product.id)}} className="p-2 rounded-full bg-white/90 text-[#9E1236] shadow-md"><Heart className={`w-4 h-4 ${favorites.includes(product.id)?'fill-[#E11D48]':''}`}/></button>;
  return <section id="menu-highlights" className="relative pt-16 sm:pt-24 pb-28 sm:pb-36 bg-gradient-to-b from-[#7A0D28] via-[#8C1030] to-[#5C081D] overflow-hidden text-white">
    <div className="absolute inset-0 bg-sprinkles-white opacity-20"/><div className="absolute top-1/4 -right-28 w-[700px] h-[700px] bg-[#E11D48]/20 rounded-full blur-3xl"/><div className="absolute bottom-1/4 left-0 w-[600px] h-[600px] bg-[#F59E0B]/10 rounded-full blur-3xl"/>
    <div className="max-w-[1380px] mx-auto px-4 sm:px-6 lg:px-10 relative z-10">
      <div className="text-center relative max-w-4xl mx-auto mb-12 sm:mb-16"><div className="hidden sm:block absolute -top-8 -left-10 rotate-[-12deg] bg-[#FFF8F0] border-2 border-[#FDE68A] px-4 py-1.5 rounded-2xl shadow-sweet"><span className="font-script text-3xl text-[#7A0D28] font-bold">Chef's Choice! ♡</span></div><div className="inline-flex items-center gap-2 bg-white/15 px-4 py-1.5 rounded-full border border-white/25 mb-3"><Sparkles className="w-3.5 h-3.5 text-[#FDE68A]"/><p className="text-[11px] font-extrabold tracking-[.26em] text-[#FED7AA]">THE DESSERT SHOWCASE • 10 SIGNATURE CREATIONS</p></div><h2 className="font-serif text-3xl sm:text-5xl lg:text-[58px] font-bold">Something Sweet for Every Mood</h2><p className="mt-3 text-[#FED7AA]/90">From towering celebration cakes to artisan dipped berries and seasonal treats — handcrafted daily in Houston.</p></div>
      <div className="grid lg:grid-cols-12 gap-6 mb-10">
        <article onClick={()=>onSelectProduct(strawberries)} className="lg:col-span-7 group rounded-[44px] overflow-hidden border-4 border-white/90 shadow-2xl cursor-pointer relative bg-[#1E0C08]"><div className="absolute top-3 left-8 z-30"><WashiTape className="w-28 h-5" color="#FED7AA"/></div><img src={strawberries.image} className="w-full aspect-[16/10] object-cover group-hover:scale-105 transition duration-700"/><div className="absolute inset-0 bg-gradient-to-t from-[#1A0805] via-transparent to-black/10"/><div className="absolute top-5 left-5 bg-[#9E1236] rounded-full px-3 py-1.5 font-bold">🔥 #1 Best Seller</div><div className="absolute top-5 right-5">{heart(strawberries)}</div><div className="absolute bottom-6 left-6 right-6"><div className="font-script text-3xl text-[#FDE68A]">Hand-dipped with Belgian Chocolate ♡</div><h3 className="font-serif text-3xl sm:text-4xl font-bold">{strawberries.name}</h3><div className="mt-3 pt-3 border-t border-white/20 flex flex-wrap justify-between gap-3"><span className="font-serif text-xl text-[#FDE68A]">{strawberries.priceTag}</span><button onClick={e=>{e.stopPropagation();onQuickOrder(strawberries)}} className="bg-[#9E1236] px-5 py-2 rounded-full font-bold flex gap-2 items-center">Order Batch <ArrowRight className="w-4 h-4"/></button></div></div></article>
        <article onClick={()=>onSelectProduct(unicorn)} className="lg:col-span-5 group rounded-t-[80px] rounded-b-[44px] overflow-hidden border-4 border-white/90 shadow-2xl cursor-pointer relative bg-[#2D1226]"><img src={unicorn.image} className="w-full h-full min-h-[520px] object-cover group-hover:scale-105 transition duration-700"/><div className="absolute inset-0 bg-gradient-to-t from-black/75 via-transparent to-transparent"/><div className="absolute top-6 left-6 bg-[#9333EA] px-3 py-1.5 rounded-full font-bold">Pastel Dream 🦄</div><div className="absolute top-6 right-6">{heart(unicorn)}</div><div className="absolute bottom-7 left-7 right-7"><span className="font-script text-2xl text-[#E9D5FF]">Fantasy Centerpiece</span><h3 className="font-serif text-3xl font-bold">{unicorn.name}</h3><div className="mt-3 pt-3 border-t border-white/20 flex justify-between"><span>{unicorn.servings}</span><span className="bg-white text-[#240F0B] px-3 py-1 rounded-full font-bold">{unicorn.priceTag}</span></div></div></article>
      </div>
      <div className="grid md:grid-cols-3 gap-6 mb-10 items-center">
        {[birthday, strawberry].map((x,i)=><article key={x.id} onClick={()=>onSelectProduct(x)} className={`bg-[#FFFDF9] p-4 rounded-3xl shadow-2xl cursor-pointer text-[#240F0B] ${i===0?'-rotate-1':'rotate-1'} hover:rotate-0 transition`}><div className="relative"><img src={x.image} className="w-full aspect-square object-cover rounded-2xl"/><div className="absolute top-3 right-3">{heart(x)}</div></div><div className="pt-3 flex justify-between gap-2"><h3 className="font-serif text-xl font-bold">{x.name}</h3><span className="text-xs font-bold text-[#9E1236] bg-[#FFF2EE] px-2 py-1 rounded-full">{x.priceTag}</span></div></article>)}
        <article onClick={()=>onSelectProduct(cupcake)} className="group flex flex-col items-center text-center cursor-pointer"><div className="font-script text-3xl text-[#FDE68A] mb-2">The Cloud Swirl 🧁</div><div className="relative w-64 h-64 rounded-full overflow-hidden border-4 border-[#FED7AA] shadow-2xl"><img src={cupcake.image} className="w-full h-full object-cover group-hover:scale-110 transition duration-700"/><div className="absolute top-3 right-3">{heart(cupcake)}</div></div><h3 className="font-serif text-2xl font-bold mt-3">{cupcake.name}</h3><span className="text-xs font-bold text-[#7A0D28] bg-[#FDE68A] px-3 py-1 rounded-full">{cupcake.priceTag}</span></article>
      </div>
      <div className="grid md:grid-cols-12 gap-6 mb-10">
        {[champagne,pumpkin,pretzel].map((x,i)=><article key={x.id} onClick={()=>onSelectProduct(x)} className={`${i===0?'md:col-span-5 bg-[#180806] text-white':i===1?'md:col-span-3 bg-[#F4E2C8] text-[#240F0B]':'md:col-span-4 bg-[#FFFDF9] text-[#240F0B]'} rounded-[32px] overflow-hidden shadow-2xl cursor-pointer`}><img src={x.image} className="w-full aspect-[4/3] object-cover"/><div className="p-5 flex justify-between items-end gap-3"><div><h3 className="font-serif text-xl font-bold">{x.name}</h3><p className="text-xs opacity-75 mt-1">{x.flavorNotes?.[0]}</p></div><span className="text-xs font-bold px-2.5 py-1 rounded-full bg-[#9E1236] text-white">{x.priceTag}</span></div></article>)}
      </div>
      <div className="grid md:grid-cols-2 gap-6 mb-10">
        {[upside,ginger].map(x=><article key={x.id} onClick={()=>onSelectProduct(x)} className="group bg-[#FFFDF9] text-[#240F0B] rounded-[36px] overflow-hidden shadow-2xl cursor-pointer flex flex-col sm:flex-row border-3 border-white"><img src={x.image} className="w-full sm:w-7/12 aspect-[4/3] object-cover"/><div className="p-6 flex-1 flex flex-col justify-between"><div><h3 className="font-serif text-2xl font-bold">{x.name}</h3><p className="text-xs text-[#552A20] mt-2">{x.description}</p></div><div className="pt-3 flex justify-between"><span className="font-serif font-bold text-[#9E1236]">{x.priceTag}</span><span className="font-bold">Explore →</span></div></div></article>)}
      </div>
      <div className="mt-14 bg-white/95 text-[#240F0B] rounded-3xl p-6 sm:p-8 border-2 border-white shadow-2xl flex flex-col md:flex-row items-center justify-between gap-6"><div><p className="font-script text-3xl text-[#9E1236] font-bold">Can't find your exact dream flavor? ♡</p><p className="text-sm text-[#552A20]">We specialize in custom party themes, corporate dessert boxes, and tiered event showstoppers.</p></div><button onClick={()=>onQuickOrder(strawberries)} className="px-6 py-3 rounded-full bg-[#9E1236] text-white font-bold flex items-center gap-2">Request Custom Flavor <ArrowRight className="w-4 h-4"/></button></div>
    </div><div className="absolute bottom-0 left-0 right-0"><WavyCreamDivider fillColor="#FFF7ED" className="w-full h-20"/></div>
  </section>;
};
